// service-worker.js — gerado pelo Mini SK em 03/10/2026, 02:01:40
// Não precisa mexer: ele guarda sozinho o que o app usa.
const PREFIXO = 'sk-sk-juridico-v1-7-0-electron-7-';
const CACHE = PREFIXO + 'murxczy0';
// Lista feita automaticamente (para funcionar sem internet logo após instalar)
const GUARDAR = [
  "./",
  "./.env.example.txt",
  "./artifacts/api-server/build.mjs",
  "./artifacts/api-server/package.json",
  "./artifacts/api-server/src/app.ts",
  "./artifacts/api-server/src/file-storage.ts",
  "./artifacts/api-server/src/index.ts",
  "./artifacts/api-server/src/lib/logger.ts",
  "./artifacts/api-server/src/local-config.ts",
  "./artifacts/api-server/src/middleware/jwt-auth.ts",
  "./artifacts/api-server/src/routes/ai.ts",
  "./artifacts/api-server/src/routes/assinatura.ts",
  "./artifacts/api-server/src/routes/auth-jwt.ts",
  "./artifacts/api-server/src/routes/colaborativo.ts",
  "./artifacts/api-server/src/routes/crud.ts",
  "./artifacts/api-server/src/routes/drive-sync.ts",
  "./artifacts/api-server/src/routes/extra.ts",
  "./artifacts/api-server/src/routes/health.ts",
  "./artifacts/api-server/src/routes/index.ts",
  "./artifacts/api-server/src/routes/integracoes.ts",
  "./artifacts/api-server/src/routes/jurisprudencia.ts",
  "./artifacts/api-server/src/routes/pje.ts",
  "./artifacts/api-server/src/routes/prazos.ts",
  "./artifacts/api-server/src/routes/settings.ts",
  "./artifacts/api-server/src/routes/status.ts",
  "./artifacts/api-server/src/routes/upload.ts",
  "./artifacts/api-server/src/storage.ts",
  "./artifacts/api-server/tsconfig.json",
  "./artifacts/assistente-juridico/404.html",
  "./artifacts/assistente-juridico/favicon.ico",
  "./artifacts/assistente-juridico/icons/apple-touch-icon.png",
  "./artifacts/assistente-juridico/icons/icon-16.png",
  "./artifacts/assistente-juridico/icons/icon-32.png",
  "./artifacts/assistente-juridico/icons/icon-48.png",
  "./artifacts/assistente-juridico/icons/icon-72.png",
  "./artifacts/assistente-juridico/icons/icon-96.png",
  "./artifacts/assistente-juridico/icons/icon-128.png",
  "./artifacts/assistente-juridico/icons/icon-144.png",
  "./artifacts/assistente-juridico/icons/icon-152.png",
  "./artifacts/assistente-juridico/icons/icon-180.png",
  "./artifacts/assistente-juridico/icons/icon-192.png",
  "./artifacts/assistente-juridico/icons/icon-384.png",
  "./artifacts/assistente-juridico/icons/icon-512.png",
  "./artifacts/assistente-juridico/icons/icon.svg",
  "./artifacts/assistente-juridico/icons/maskable-192.png",
  "./artifacts/assistente-juridico/icons/maskable-512.png",
  "./artifacts/assistente-juridico/icons/maskable.svg",
  "./artifacts/assistente-juridico/index.html",
  "./artifacts/assistente-juridico/manifest.json",
  "./artifacts/assistente-juridico/package.json",
  "./artifacts/assistente-juridico/public/favicon.svg",
  "./artifacts/assistente-juridico/public/icon-192.png",
  "./artifacts/assistente-juridico/public/icon-512.png",
  "./artifacts/assistente-juridico/public/manifest.json",
  "./artifacts/assistente-juridico/public/opengraph.jpg",
  "./artifacts/assistente-juridico/public/robots.txt",
  "./artifacts/assistente-juridico/public/sw.js",
  "./artifacts/assistente-juridico/service-worker.js",
  "./artifacts/assistente-juridico/src/App.tsx",
  "./artifacts/assistente-juridico/src/components/pwa-install.tsx",
  "./artifacts/assistente-juridico/src/components/theme-provider.tsx",
  "./artifacts/assistente-juridico/src/components/theme-toggle.tsx",
  "./artifacts/assistente-juridico/src/components/tiptap-editor.tsx",
  "./artifacts/assistente-juridico/src/components/ui/accordion.tsx",
  "./artifacts/assistente-juridico/src/components/ui/alert-dialog.tsx",
  "./artifacts/assistente-juridico/src/components/ui/alert.tsx",
  "./artifacts/assistente-juridico/src/components/ui/aspect-ratio.tsx",
  "./artifacts/assistente-juridico/src/components/ui/avatar.tsx",
  "./artifacts/assistente-juridico/src/components/ui/badge.tsx",
  "./artifacts/assistente-juridico/src/components/ui/breadcrumb.tsx",
  "./artifacts/assistente-juridico/src/components/ui/button-group.tsx",
  "./artifacts/assistente-juridico/src/components/ui/button.tsx",
  "./artifacts/assistente-juridico/src/components/ui/calendar.tsx",
  "./artifacts/assistente-juridico/src/components/ui/card.tsx",
  "./artifacts/assistente-juridico/src/components/ui/carousel.tsx",
  "./artifacts/assistente-juridico/src/components/ui/chart.tsx",
  "./artifacts/assistente-juridico/src/components/ui/checkbox.tsx",
  "./artifacts/assistente-juridico/src/components/ui/collapsible.tsx",
  "./artifacts/assistente-juridico/src/components/ui/command.tsx",
  "./artifacts/assistente-juridico/src/components/ui/context-menu.tsx",
  "./artifacts/assistente-juridico/src/components/ui/dialog.tsx",
  "./artifacts/assistente-juridico/src/components/ui/drawer.tsx",
  "./artifacts/assistente-juridico/src/components/ui/dropdown-menu.tsx",
  "./artifacts/assistente-juridico/src/components/ui/empty.tsx",
  "./artifacts/assistente-juridico/src/components/ui/field.tsx",
  "./artifacts/assistente-juridico/src/components/ui/form.tsx",
  "./artifacts/assistente-juridico/src/components/ui/hover-card.tsx",
  "./artifacts/assistente-juridico/src/components/ui/input-group.tsx",
  "./artifacts/assistente-juridico/src/components/ui/input-otp.tsx",
  "./artifacts/assistente-juridico/src/components/ui/input.tsx",
  "./artifacts/assistente-juridico/src/components/ui/item.tsx",
  "./artifacts/assistente-juridico/src/components/ui/kbd.tsx",
  "./artifacts/assistente-juridico/src/components/ui/label.tsx",
  "./artifacts/assistente-juridico/src/components/ui/menubar.tsx",
  "./artifacts/assistente-juridico/src/components/ui/navigation-menu.tsx",
  "./artifacts/assistente-juridico/src/components/ui/pagination.tsx",
  "./artifacts/assistente-juridico/src/components/ui/popover.tsx",
  "./artifacts/assistente-juridico/src/components/ui/progress.tsx",
  "./artifacts/assistente-juridico/src/components/ui/radio-group.tsx",
  "./artifacts/assistente-juridico/src/components/ui/resizable.tsx",
  "./artifacts/assistente-juridico/src/components/ui/scroll-area.tsx",
  "./artifacts/assistente-juridico/src/components/ui/select.tsx",
  "./artifacts/assistente-juridico/src/components/ui/separator.tsx",
  "./artifacts/assistente-juridico/src/components/ui/sheet.tsx",
  "./artifacts/assistente-juridico/src/components/ui/sidebar.tsx",
  "./artifacts/assistente-juridico/src/components/ui/skeleton.tsx",
  "./artifacts/assistente-juridico/src/components/ui/slider.tsx",
  "./artifacts/assistente-juridico/src/components/ui/sonner.tsx",
  "./artifacts/assistente-juridico/src/components/ui/spinner.tsx",
  "./artifacts/assistente-juridico/src/components/ui/switch.tsx",
  "./artifacts/assistente-juridico/src/components/ui/table.tsx",
  "./artifacts/assistente-juridico/src/components/ui/tabs.tsx",
  "./artifacts/assistente-juridico/src/components/ui/textarea.tsx",
  "./artifacts/assistente-juridico/src/components/ui/toast.tsx",
  "./artifacts/assistente-juridico/src/components/ui/toaster.tsx",
  "./artifacts/assistente-juridico/src/components/ui/toggle-group.tsx",
  "./artifacts/assistente-juridico/src/components/ui/toggle.tsx",
  "./artifacts/assistente-juridico/src/components/ui/tooltip.tsx",
  "./artifacts/assistente-juridico/src/hooks/use-mobile.tsx",
  "./artifacts/assistente-juridico/src/hooks/use-toast.ts",
  "./artifacts/assistente-juridico/src/index.css",
  "./artifacts/assistente-juridico/src/lib/legal-formatter.ts",
  "./artifacts/assistente-juridico/src/lib/queryClient.ts",
  "./artifacts/assistente-juridico/src/lib/sync-storage.ts",
  "./artifacts/assistente-juridico/src/lib/utils.ts",
  "./artifacts/assistente-juridico/src/main.tsx",
  "./artifacts/assistente-juridico/src/pages/admin.tsx",
  "./artifacts/assistente-juridico/src/pages/assinatura.tsx",
  "./artifacts/assistente-juridico/src/pages/auditoria-financeira.tsx",
  "./artifacts/assistente-juridico/src/pages/codigo.tsx",
  "./artifacts/assistente-juridico/src/pages/colaborativo.tsx",
  "./artifacts/assistente-juridico/src/pages/comparador-juridico.tsx",
  "./artifacts/assistente-juridico/src/pages/comunicacoes-cnj.tsx",
  "./artifacts/assistente-juridico/src/pages/configuracoes.tsx",
  "./artifacts/assistente-juridico/src/pages/consulta-corporativo.tsx",
  "./artifacts/assistente-juridico/src/pages/consulta-pdpj.tsx",
  "./artifacts/assistente-juridico/src/pages/consulta-processual.tsx",
  "./artifacts/assistente-juridico/src/pages/ementas.tsx",
  "./artifacts/assistente-juridico/src/pages/escritorio.tsx",
  "./artifacts/assistente-juridico/src/pages/filtrador.tsx",
  "./artifacts/assistente-juridico/src/pages/historico.tsx",
  "./artifacts/assistente-juridico/src/pages/jurisprudencia.tsx",
  "./artifacts/assistente-juridico/src/pages/legal-assistant.tsx",
  "./artifacts/assistente-juridico/src/pages/login.tsx",
  "./artifacts/assistente-juridico/src/pages/not-found.tsx",
  "./artifacts/assistente-juridico/src/pages/painel-processos.tsx",
  "./artifacts/assistente-juridico/src/pages/pje.tsx",
  "./artifacts/assistente-juridico/src/pages/playground.tsx",
  "./artifacts/assistente-juridico/src/pages/prazos.tsx",
  "./artifacts/assistente-juridico/src/pages/previdenciario.tsx",
  "./artifacts/assistente-juridico/src/pages/robo-djen.tsx",
  "./artifacts/assistente-juridico/src/pages/status.tsx",
  "./artifacts/assistente-juridico/src/pages/templates-juridicos.tsx",
  "./artifacts/assistente-juridico/src/pages/token-generator.tsx",
  "./artifacts/assistente-juridico/src/pages/tramitacao.tsx",
  "./artifacts/assistente-juridico/tsconfig.json",
  "./artifacts/assistente-juridico/vite.config.ts",
  "./artifacts/desktop/main.js",
  "./artifacts/desktop/package.json",
  "./artifacts/desktop/preload.js",
  "./capacitor.config.ts",
  "./docker-compose.yml",
  "./favicon.ico",
  "./icons/apple-touch-icon.png",
  "./icons/icon-16.png",
  "./icons/icon-32.png",
  "./icons/icon-48.png",
  "./icons/icon-72.png",
  "./icons/icon-96.png",
  "./icons/icon-128.png",
  "./icons/icon-144.png",
  "./icons/icon-152.png",
  "./icons/icon-180.png",
  "./icons/icon-192.png",
  "./icons/icon-384.png",
  "./icons/icon-512.png",
  "./icons/icon.svg",
  "./icons/maskable-192.png",
  "./icons/maskable-512.png",
  "./icons/maskable.svg",
  "./index.html",
  "./lib/db/drizzle.config.ts",
  "./lib/db/package.json",
  "./lib/db/src/index.ts",
  "./lib/db/src/schema/index.ts",
  "./lib/db/tsconfig.json",
  "./lib/sync-storage/src/index.ts",
  "./manifest.json",
  "./MANUAL.md",
  "./package.json",
  "./pnpm-workspace.yaml",
  "./scripts/src/hello.ts",
  "./start-local.sh",
  "./tsconfig.base.json",
  "./tsconfig.json"
];

self.addEventListener('install', (e) => {
  self.skipWaiting();
  e.waitUntil(caches.open(CACHE).then((c) => Promise.all(GUARDAR.map((u) => c.add(u).catch(() => null)))));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((ks) => Promise.all(ks.filter((k) => k.startsWith(PREFIXO) && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// Primeiro a internet (sempre a versão nova); sem internet, a cópia guardada.
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(
    fetch(req).then((res) => {
      if (res.ok) { const copia = res.clone(); caches.open(CACHE).then((c) => c.put(req, copia)); }
      // Igual ao Workbox da Replit: página que não existe (rota do app) abre o index
      if (res.status === 404 && req.mode === 'navigate') return caches.match('./').then((r) => r || fetch('./'));
      return res;
    }).catch(() => caches.match(req, { ignoreSearch: true }).then((r) => r || (req.mode === 'navigate' ? caches.match('./') : undefined)))
  );
});
